/**
 * AIET-UniSphere - Gemini API Client
 * Secure server-side interface for Google Gemini API.
 * Never logs secrets or returns raw API keys in errors.
 */

import { GenerateRequest, GenerateResponse } from "./types.ts";

/**
 * Validates Gemini environment configuration and returns sanitized settings.
 */
export function getGeminiConfig(): { apiKey: string; model: string } {
  // @ts-ignore Deno global
  const apiKey = Deno.env.get("GEMINI_API_KEY");
  if (!apiKey || apiKey.trim().length === 0) {
    throw new Error("GEMINI_API_KEY is not configured in Supabase Edge Function secrets.");
  }

  // Model fallback to gemini-1.5-flash which is widely supported and cost-efficient
  // @ts-ignore Deno global
  const model = Deno.env.get("GEMINI_MODEL") || "gemini-1.5-flash";

  return { apiKey: apiKey.trim(), model: model.trim() };
}

/**
 * Calls the Google Gemini REST API securely.
 */
export async function generateWithGemini(req: GenerateRequest): Promise<GenerateResponse> {
  const { apiKey, model } = getGeminiConfig();
  const endpoint = `https://generativelanguage.googleapis.com/v1beta/models/${encodeURIComponent(model)}:generateContent?key=${apiKey}`;

  // Build message sequence
  const contents: Array<{ role: 'user' | 'model'; parts: Array<{ text: string }> }> = [];

  if (req.history && req.history.length > 0) {
    for (const msg of req.history) {
      if (!msg.content || typeof msg.content !== 'string') continue;
      const role = msg.role === 'ai' || msg.role === 'assistant' || msg.role === 'model'
        ? 'model'
        : 'user';
      contents.push({
        role,
        parts: [{ text: msg.content.substring(0, 4000) }]
      });
    }
  }

  // Ensure current user message is appended
  contents.push({
    role: 'user',
    parts: [{ text: req.userMessage.substring(0, 4000) }]
  });

  const requestBody = {
    systemInstruction: {
      parts: [{ text: req.systemPrompt }]
    },
    contents,
    generationConfig: {
      temperature: req.temperature ?? 0.7,
      maxOutputTokens: req.maxTokens ?? 2048,
      topP: 0.95,
    },
    safetySettings: [
      { category: "HARM_CATEGORY_HARASSMENT", threshold: "BLOCK_MEDIUM_AND_ABOVE" },
      { category: "HARM_CATEGORY_HATE_SPEECH", threshold: "BLOCK_MEDIUM_AND_ABOVE" },
      { category: "HARM_CATEGORY_SEXUALLY_EXPLICIT", threshold: "BLOCK_MEDIUM_AND_ABOVE" },
      { category: "HARM_CATEGORY_DANGEROUS_CONTENT", threshold: "BLOCK_MEDIUM_AND_ABOVE" }
    ]
  };

  const controller = new AbortController();
  const timeoutMs = 30000;
  const timeoutId = setTimeout(() => controller.abort(), timeoutMs);

  let response: Response;
  try {
    response = await fetch(endpoint, {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
      },
      body: JSON.stringify(requestBody),
      signal: controller.signal,
    });
  } catch (err: unknown) {
    clearTimeout(timeoutId);
    if (err instanceof Error && err.name === "AbortError") {
      throw new Error("AI request timed out after 30 seconds. Please try again.");
    }
    const safeMsg = err instanceof Error ? err.message.replace(/key=[^&\s]+/gi, "key=REDACTED") : "Network failure";
    throw new Error(`Gemini connection error: ${safeMsg}`);
  } finally {
    clearTimeout(timeoutId);
  }

  if (!response.ok) {
    let errorDetail = "";
    try {
      const errorJson = await response.json();
      errorDetail = errorJson?.error?.message || response.statusText;
    } catch {
      errorDetail = await response.text().catch(() => "");
    }

    // Sanitize any key leakage from error message
    const sanitizedError = errorDetail.replace(/key=[^&\s]+/gi, "key=REDACTED");

    if (response.status === 429) {
      throw new Error("AI rate limit reached. Please wait a moment before trying again.");
    }
    if (response.status === 403 || response.status === 401) {
      throw new Error("Invalid Gemini API credentials configured on server.");
    }
    if (response.status === 404) {
      throw new Error(`Configured Gemini model '${model}' was not found. Check GEMINI_MODEL setting.`);
    }

    throw new Error(`Gemini API error (${response.status}): ${sanitizedError || "Unknown error"}`);
  }

  let data: any;
  try {
    data = await response.json();
  } catch {
    throw new Error("Failed to parse Gemini response payload.");
  }

  const candidate = data?.candidates?.[0];
  if (!candidate) {
    if (data?.promptFeedback?.blockReason) {
      throw new Error(`Request was blocked by safety policy: ${data.promptFeedback.blockReason}`);
    }
    throw new Error("No response generated by the AI model.");
  }

  if (candidate.finishReason === "SAFETY") {
    throw new Error("The response was flagged by safety filters. Please rephrase your academic query.");
  }

  const textPart = candidate.content?.parts?.find((p: any) => typeof p.text === 'string');
  const text = textPart?.text || "";

  if (!text.trim()) {
    throw new Error("Empty response returned by the AI model.");
  }

  const inputTokens = data?.usageMetadata?.promptTokenCount;
  const outputTokens = data?.usageMetadata?.candidatesTokenCount;
  const tokensUsed = data?.usageMetadata?.totalTokenCount ?? (
    inputTokens && outputTokens ? inputTokens + outputTokens : undefined
  );

  return {
    text,
    tokensUsed,
    inputTokens,
    outputTokens,
    provider: "gemini",
    model,
  };
}
